name: Build and Test Chrome Extension
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build Extension
        run: npm run build
      - name: Archive Extension
        run: |
          zip -r dist/extension.zip dist/*
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: dist/extension.zip
      - name: Run Tests
        run: npm run test
